[package]
name = "cross-validation"
version = "0.1.0"
authors = ["Elías Puma <elpumitaelias@gmail.com>"]

[dependencies]
distance = { path = "../../libs/distance/" }
database = { path = "../../libs/database/" }